ndlib/zucchetto

src/components/Notebook/DisplayDocument.jsx
src/components/Notebook/Notebook.jsx
src/store/ItemStore.js

I added parents and children to the display document.

refactor item store to have children in order.

---

src/components/Notebook/NotebookLink.jsx
src/components/Search/SearchBox.jsx
src/components/Search/SearchByDate.jsx
src/components/Search/SearchByDocumentType.jsx
src/components/Search/SearchByGeographicRegion.jsx
src/components/Search/SearchByTopic.jsx
src/components/Search/SearchSidebar.jsx
src/mixins/LoadRemoteMixin.jsx
src/modules/ListItemStyle.js

Mostly style things and stubbing out search facet stuff.

style search page

---

src/components/Document/Document.jsx
src/components/Document/DownloadPDF.jsx
src/components/Document/Paragraph.jsx
src/components/Notebook/Notebook.jsx

Documents have a remove link so you don't have to see them in a column in the notebook and there is a download pdf link.

added a remove link and the download pdf link.

---

src/components/Notebook/Notebook.jsx
src/components/Notebook/NotebookColumn.jsx
src/components/Notebook/NotebookDocument.jsx
src/components/Notebook/NotebookList.jsx

I also refactored the way the display so that it is a little more user friendly.

Add remove link to docuement and added second column display

---

src/assets/css/csthr.scss
src/components/Document/Document.jsx
src/components/Document/Paragraph.jsx
src/components/Notebook/Notebook.jsx
src/components/Notebook/NotebookColumn.jsx
src/components/Notebook/NotebookList.jsx
src/store/ItemStore.js

added a selected class to the selected paragraph.

Add selected paragraph

---

src/assets/css/csthr.scss
src/assets/css/document.scss
src/assets/css/main.scss
src/components/Document/CurrentParagraph.jsx
src/components/Document/Document.jsx
src/components/Document/Paragraph.jsx
src/components/Document/Title.jsx
src/components/Notebook/NotebookDocument.jsx
src/components/Search/ListItem.jsx

I added a mechanism to scroll automatically to the selected paragraph. 
I also consolidated a few of the classes and styles.

add auto scrolling to selected document element. 

---

src/assets/css/document.scss
src/components/Document/AddToCompare.jsx
src/components/Document/DocumentCard.jsx
src/components/Notebook/NotebookColumn.jsx
src/components/Notebook/NotebookList.jsx
src/components/Search/ListItem.jsx

add documents

---

src/actions/CompareActions.js
src/components/Document/AddToCompare.jsx
src/constants/CompareActionTypes.jsx
src/modules/CheckLocalStorage.js
src/store/CompareStore.js

Code to add comparisons in the store.

Add store for comparison tool

---

src/components/Notebook/Notebook.jsx
src/components/Notebook/NotebookColumn.jsx
src/components/Notebook/NotebookList.jsx
src/routes/NotebookPage.jsx

I updated the compare page to use the store instead of passed in params.

Update compare page to use comparestore

---

src/actions/CompareActions.js
src/components/Notebook/Notebook.jsx
src/components/Notebook/NotebookColumn.jsx
src/constants/CompareActionTypes.jsx
src/store/CompareStore.js

I updated the compare page to have a select a single document at a time.

update compare to have a better flow for displaying.

---

src/components/Document/Paragraph.jsx
src/components/Notebook/NotebookLink.jsx
src/components/Search/Drawer.jsx
src/components/Search/ListItem.jsx
src/components/Search/SearchByGeographicRegion.jsx
src/routes/SearchPage.jsx

First pass at adding a drawer that show number of documents currently selected for comparison.

Adding comparison drawer on search page

---

src/assets/css/csthr.scss
src/assets/css/document.scss
src/components/Document/Document.jsx
src/components/Document/DocumentCard.jsx
src/components/Document/DocumentListItem.jsx
src/components/Document/DownloadPDF.jsx
src/components/Document/Paragraph.jsx
src/components/Notebook/Notebook.jsx
src/components/Notebook/NotebookColumn.jsx
src/components/Notebook/NotebookDocument.jsx
src/components/Notebook/NotebookList.jsx
src/components/Search/ListItem.jsx
src/components/Search/Search.jsx
src/components/Search/SearchByGeographicRegion.jsx
src/components/Shared/Heading.jsx
src/components/StaticAssets/Footer.jsx
src/components/StaticAssets/Header.jsx
src/routes/SearchPage.jsx
src/store/CompareStore.js

updates to the overall ui of the site with some changes to the compare page

Update compare ui

---

src/components/Search/ChildValue.js
src/components/Search/SearchByTopic.jsx
src/components/Search/SearchDisplayList.jsx
src/components/Search/SearchSidebar.jsx
src/components/Search/TopicFacet.jsx
src/components/Search/TopicFacets.jsx
src/components/Search/topics.js

What? Create facets for the search interface.
How? Build a nested list based on a javascript object that appends additional values to the current search term to 'search by topics'

Dec 822 - Add facets

---

src/components/Search/SearchBox.jsx
src/components/Search/TopicFacet.jsx

* Leave search term in search box
* Bold selected facet terms
* Expand selected Facets
* Pointer cursor on facet hover

Style fixes for DEC-822

---

src/components/Notebook/EmptyColumn.jsx
src/components/Notebook/Notebook.jsx
src/components/Notebook/NotebookColumn.jsx

I added a place holder to the compare page when there are no documents in the column

add the empty column to the compare page.

---

src/components/Notebook/NotebookList.jsx

updated side nav to have titles.

update to add separators in the type of documents.

---

src/components/Search/SearchSidebar.jsx
src/components/Search/topics.js
src/routes/SearchPage.jsx

* Increased width of left column to accomodate long titles.
* Based on "Actors 031716.docx"

Load topics from actual topic lists.

---

src/components/Notebook/Notebook.jsx
src/components/Notebook/NotebookLink.jsx
src/components/Notebook/NotebookList.jsx
src/components/StaticAssets/Header.jsx
src/components/StaticAssets/Navigation.jsx
src/components/StaticPages/SiteIndex.jsx
src/routes/DocumentPage.jsx
src/routes/NotebookPage.jsx
src/routes/Page.jsx
src/routes/SearchPage.jsx
src/routes/routes.js
src/store/ItemStore.js

Which takes the adventure further than ever before and adds the correct router linking to all the sections except for the search. 
As a side note.  Search was omitted because it will need to be reimplemented with a Store, Actions and events because it is currently bound to the page re-rendering the components to change search results. Making the call the router only updates the url (and history) because we are not actually going to a new page.

Dec 824 part the second

---

src/components/Document/DocumentParagraphListItem.jsx
src/components/Document/Paragraph.jsx
src/modules/HoneycombURL.js

fix bug displaying styling for paragraphs. 

---

src/routes/SearchPage.jsx

Changed to render a "Get started" type page whenever the search term is empty.

DEC-891: Add a empty search result page with what a person should do

---

src/components/Document/AddToCompare.jsx
src/components/Document/CompareButton.jsx
src/components/Notebook/NotebookLink.jsx
src/components/Notebook/NotebookList.jsx
src/components/Search/Drawer.jsx
src/routes/SearchPage.jsx
src/store/CompareStore.js

update the compare drawer to work with the button 

---

src/assets/css/document.scss
src/components/Document/AddToCompare.jsx
src/components/Document/CompareButton.jsx
src/components/Notebook/NotebookLink.jsx
src/components/Notebook/NotebookList.jsx
src/components/Search/Drawer.jsx
src/components/Search/SearchDisplayList.jsx
src/components/Search/SearchSidebar.jsx
src/routes/SearchPage.jsx
src/store/CompareStore.js

I updated the search results so that there is one scroll bar and it is the height of the search area.

Update to set the height of search

---

src/components/Document/DocumentCard.jsx

-Removed the metadata option
-Fixed a problem with windows line endings in the file
-Removed the tool tip on the icon button for now, was causing overflow problems when the card was collapsed.

Hide Metadata ? in the menu

---

src/assets/css/document.scss
src/components/Document/Document.jsx
src/components/Document/Paragraph.jsx
src/components/Notebook/NotebookDocument.jsx

Set height on NotebookDocument.
Scroll the document to the appropriate place when the jump list is changed.

Document selection list action

---

src/components/Document/CopyrightNotification.jsx

-metadata.rights has become rights_holder_website in the configuration for vatican and humanrights collections

DEC-893: Fix Missing Rights holder title and url.

---

src/components/Document/Document.jsx
src/components/Document/ParagraphJumpList.jsx

* Filter jump list options to only selected paragraphs.
* Added text telling user what jump list does.

Filter jump list options to only selected paragraphs.

---

src/components/Document/BackToSearchButton.jsx
src/components/Notebook/Notebook.jsx
src/components/Search/TopicFacet.jsx
src/components/Search/topics.js
src/components/StaticAssets/Footer.jsx
src/routes/SearchPage.jsx

* Remove compare drawer doesn't work on the Notebook page
* Put back to search page button on compare page where drawer toggle is on search page.
* Fixed  garbled text in "Government/The State"
* Fixed alignment on lines with break such as  "detained persons" and "imprisoned persons"

Some other thoughts email

---

src/components/StaticAssets/Header.jsx
src/routes/AllDocumentsPage.jsx
src/routes/SearchPage.jsx
src/routes/routes.js
src/store/ItemStore.js

Simple page that displays all the documents.  I view this as a stepping stone to getting to help guide the development of what the document index should do.

added very basic view of the document index.

---

package.json
src/routes/routes.js

* Created new Google Analytics code.
* Added react-ga library, so this will require running an `npm install`.

Add Google Analytics

---

src/components/Document/ShareSave.jsx

Modal with directions on how to copy url and some fancy stuff to allow
clicking on the url or a button to automagically add it to the
clipboard.

DEC-826 Add a share/save modal

---

src/components/Document/CompareButton.jsx
src/components/Notebook/NotebookLink.jsx
src/components/Search/Drawer.jsx
src/routes/SearchPage.jsx

Updated the display of the drawer to be full width.

DEC-900 New ui for comparison drawer

---

src/components/Document/Document.jsx
src/components/Document/DocumentType.jsx
src/components/Search/Drawer.jsx

What:  Added the document type to the display of the document.

Dec 920 add document type

---

src/components/Search/TokenSearchBox.jsx

* Change onClick to more accurate onSubmit().
* Add a callback for onSubmit() after setting the search term state in handleChange().

DEC-942 Search after each chip is added

---

src/components/Document/DocumentListItem.jsx
src/components/Notebook/NotebookList.jsx

* Use checkboxes on the left nav of the Compare page to select and de-select documents.

DEC-940 Use checkboxes on the left nav of the Compare page

---

src/components/Notebook/NotebookList.jsx
src/store/CompareStore.js

DEC-940 Checkbox was not updating when document closed through x on document.

---

package.json

* Revert build to previous version.
* Add watch to watch and build
* Run `npm run watch` instead of `npm run build` for automatic building on
file changes.

Add watch script

---

src/routes/AllDocumentsPage.jsx

* Using the source metadata field
* Uses regex to clean up additional session info from source
* Note: client will want to do some data clean up to fix groupings
with diffent capitalizations, and anomalies with of/to

DEC-939 Group International Human Rights documents

---

src/routes/AllDocumentsPage.jsx

Revert "DEC-939 Group International Human Rights documents"

---

npm-shrinkwrap.json
package.json
src/assets/css/tokens.css

Change unicode character to material-design icon.
Run:
`npm install`

Jon's x close encoding bug.

---

src/components/Document/CompareButton.jsx

This is getting ready for the upgrade for React 15 and updated Material
UI

Fix warning on CompareButton

---

src/assets/css/csthr.scss
src/components/Document/AddToCompare.jsx
src/components/Document/Paragraph.jsx
src/components/Search/ListItem.jsx

Replaced blurb with alt title, document symbol, entry into force, promulgated by, and type of document metadata fields.

DEC-956 Ammend text snippet in search results

---

src/components/Document/Document.jsx
src/components/Document/ParagraphJumpList.jsx
src/components/Notebook/NotebookColumn.jsx
src/components/Notebook/NotebookDocument.jsx

DEC-967 Fix jumpmenu

---

src/components/Document/DocumentNav.jsx
src/components/Notebook/NotebookList.jsx
src/components/Search/ListItem.jsx
src/modules/GroupItemsByParent.js
src/routes/DocumentPage.jsx

I added a menu sort to the nav that highlights saved compare values.

refactor to highlight the paragraphs saved for compare.

---

src/components/Document/CopyrightNotification.jsx
src/components/Document/DocumentNav.jsx
src/components/Document/DocumentSection.jsx
src/components/Document/DocumentToolbar.jsx
src/routes/DocumentPage.jsx

* DEC-995: Put separate scrolls on document and controls on document
page
* DEC-996: Put title back in bar on document page
* DEC-997: Move Back button to breadcrumb on document page
* DEC-998: Re-add source to document view at top of document page
* DEC-1001: Re-add view PDF to document page
* DEC-1003: Add floating link to go to top of page on document page

DEC-995 thru DEC-1003

---

src/assets/css/document.scss
src/components/Document/DocumentSection.jsx
src/components/Document/MiniMap.jsx
src/components/Document/Paragraph.jsx

* Moved tools to left
* Added minimap column
* Minimap and document scroll together at adjusted speeds.
* Clicking on mini-map jumps the main document

DEC-1002 Add document minimap

---

src/components/StaticAssets/Footer.jsx
src/components/StaticAssets/Header.jsx
src/components/StaticAssets/Navigation.jsx
src/components/StaticPages/TermsOfService.jsx
src/routes/TermsOfServicePage.jsx
src/routes/routes.js

* Add privacy policy and terms of service links to navigation area on static pages
* Add link for terms of service
* TODO: Add actuall terms of service text to TermsOfService.jsx

DEC-992 and DEC-991

---

public/index.html
src/components/Document/Document.jsx
src/components/Document/MiniMap.jsx
src/components/StaticPages/About.jsx

* Change the magic number to fix scrolling to be more accurate
* Remove console.logs that were slowing down rendering especially on
larger documents.

DEC-1024 and DEC-1023

---

src/assets/css/document.scss
src/components/Document/Document.jsx
src/components/Document/DocumentSection.jsx
src/components/Document/Paragraph.jsx
src/routes/Page.jsx

Now the document page has gray for the highlighted color and blue for the selected color.

added a different color for the highlighted paragraphs 

---

src/assets/css/document.scss
src/components/Document/AddToCompare.jsx
src/components/Document/Paragraph.jsx

Change margin to be around paragraph id instead of paragraph class.

DEC-1022 Tighten the compare button to the top of the paragraph

---

src/components/Document/MetadataSection.jsx

* Also fixed top margin to display the whole list

DEC-1020 Add the document source to the metadata tab

---

src/components/Document/DocumentToolbar.jsx
src/components/Document/MetadataSection.jsx
src/routes/DocumentPage.jsx

* Rename Metadata to Information and Document to Text in toolbar
* Highlight active section button
* Make links on metadata listing clickable
* Labels for fields bolded

Changes from Punchout for document page

---

src/assets/css/csthr.scss
src/assets/css/document.scss
src/components/Document/DocumentNav.jsx
src/components/Document/DocumentSection.jsx
src/components/Document/DocumentToolbar.jsx
src/components/Document/MetadataSection.jsx
src/components/Notebook/NotebookLink.jsx
src/components/Search/SearchSidebar.jsx
src/components/Search/TokenSearchBox.jsx
src/components/StaticAssets/Header.jsx
src/components/StaticPages/SiteIndex.jsx
src/routes/SearchPage.jsx

*  Reformat header and footer and layout stuff.
* Change compare button color on adding of items to compare.
* Some cleanup on document page layout margins.
* DEC-968 - Fix long titles in the document title bar.

Footer header

---

src/components/Document/MiniMap.jsx

Add yellow highlight to current location on minimap document. Aspect ratio taken from current browser display window.

DEC-1026 Maybe add UI to show where you are to the mini-map. 

---

src/assets/css/csthr.scss
src/components/StaticAssets/FeedbackLink.jsx
src/routes/AboutPage.jsx
src/routes/AllDocumentsPage.jsx
src/routes/ContactPage.jsx
src/routes/DocumentPage.jsx
src/routes/NotebookPage.jsx
src/routes/Page.jsx
src/routes/PartnersPage.jsx
src/routes/PrivacyPage.jsx
src/routes/ResultPage.jsx
src/routes/SearchPage.jsx
src/routes/TermsOfServicePage.jsx
src/routes/UsingPage.jsx

* fix button hover color	
* Need to add Link, linkButton is a new feature of Material UI 15 and not supported
* Need to move this out of the generic page template to get it off of the home page. Moved into individual pages.

DEC 1041 - Finalize style of feedback button. 

---

src/assets/css/document.scss
src/components/Document/DocumentSection.jsx
src/components/Document/DocumentToolbar.jsx
src/components/Document/ManageDialog.jsx
src/components/Document/ManageSaved.jsx
src/components/Document/ManageSavedItem.jsx
src/components/Document/MiniMap.jsx
src/components/Document/ShareSave.jsx
src/components/Document/ViewOriginal.jsx
src/components/Notebook/NotebookDocument.jsx
src/components/Notebook/NotebookLink.jsx
src/components/Notebook/NotebookList.jsx
src/components/Notebook/NotebookToolbar.jsx
src/components/Search/Drawer.jsx
src/components/Shared/BackButton.jsx
src/components/StaticPages/TermsOfService.jsx
src/components/StaticPages/Using.jsx
src/modules/NotebookLinkString.js

*Refactored the ShareSave component up into several smaller components for manageability and readability reasons.
* Cleaned up ui for the ManageSaved component list.
* Made the displayed list functional.
* Made changes to the Notebook component to check for updates to the compare store so i could update the NotebookList component to reflect the removal of documents while on that page.

DEC-1055 Create place to de-select items after adding them.

---

src/components/Document/ManageSaved.jsx
src/components/Document/ShareSaveDialog.jsx
src/components/Notebook/NotebookToolbar.jsx

* Split Save/Share off from Manage Documents dialog.
* Rename Manage Documents to Remove Documents to clarify that is the
only available action

Split dialogs

---

src/components/Notebook/NotebookToolbar.jsx

remove the title of the compare page.

remove text

---

src/actions/CompareActions.js
src/components/Document/ClearSavedButton.jsx
src/components/Document/ClearSavedDocumentsButton.jsx
src/components/Document/ManageSaved.jsx
src/components/Document/ManageSavedItem.jsx
src/components/Notebook/NotebookList.jsx
src/constants/CompareActionTypes.jsx
src/store/CompareStore.js

Added a clear all button to the notebook "Remove documents" dialog. It should clear all saved docs, and the current comparison.

Clear notebook

---

src/assets/css/csthr.scss
src/components/StaticPages/Partners.jsx

Fixed display of Partners page.

---

src/actions/SearchActions.js
src/components/Search/Search.jsx
src/components/Search/SearchSort.jsx
src/constants/SearchActionTypes.jsx
src/store/SearchStore.js

The sort component already existed, I have fixed it up so it will work correctly when the sort options exist and work correctly on the backend.

Fixing the sort component

---

src/assets/css/document.scss
src/components/Document/FootNotes.jsx
src/components/Search/LandingContent.jsx
src/components/Search/SearchByTopic.jsx
src/components/Search/SearchSidebar.jsx
src/routes/SearchPage.jsx

DEC-1301 
* Change 'clear' button to look like a button
DEC-1296 
* Search page column colors didn't size correctly to screen
DEC-1298
* Reduce footnotes fontsize

Restyling some vatican elements

---

src/components/Search/LandingContent.jsx
src/components/StaticPages/About.jsx

Updates in static text on search and about pages.

---

src/assets/css/csthr.scss
src/components/Search/SearchSidebar.jsx
src/routes/SearchPage.jsx

* search landing middle column is now the same color as the left column
* no more scroll bar on search page

DEC-1306 DEC-1314

---

src/components/Search/SearchByTopic.jsx
src/components/Search/topics.js

* Add top level terms from list provided by C.
* Remove the word 'Actors' from SearchByTopic component since it is now included in the top level of the search terms along with the other categories.

Update Search Terms

---

src/assets/css/csthr.scss
src/components/StaticAssets/HomePageNavigation.jsx
src/components/StaticAssets/Navigation.jsx
src/components/StaticPages/About.jsx
src/components/StaticPages/Partners.jsx
src/components/StaticPages/Using.jsx

DEC-1321: Change wording of "Useing the database" to "How to use the database"
DEC-1327: Style About and How To pages so the report a problem button doesn't overlap text

DEC-1327, DEC-1321

---

src/assets/css/csthr.scss
src/components/Search/SearchByTopic.jsx
src/components/Search/SearchSidebar.jsx

Restyle Clear button to not reduce topic list width
Restyle topic list background to always reach bottom of page with no scroll bar.

DEC-1326  DEC-1325

---

src/components/Search/topics.js

Fixing some problems with the topics sending logical operators when they shouldn't. Technically this is causing a problem with the queries now, but I found this while testing for the solr 6 upgrade, so associating it with that ticket.

Bugfix: Topic queries

---

src/assets/css/csthr.scss
src/components/Document/DocumentLink.jsx
src/components/Document/DocumentList.jsx

Added the alternate document title to the index page

DEC-1336 alternate title in document index page

---

src/actions/SearchActions.js
src/assets/css/document.scss
src/components/Search/LandingContent.jsx
src/components/Search/Search.jsx
src/components/Search/SearchDisplayList.jsx
src/components/Search/SearchSort.jsx
src/constants/SearchActionTypes.jsx
src/modules/SortBy.js
src/routes/SearchPage.jsx
src/store/SearchStore.js

Sorting options are:
* Number of Hits
* Year
* Name
* Relevance

DEC-1214 sorts

---

src/components/Search/SearchDisplayList.jsx
src/store/SearchStore.js

Minor wording changes, using correct time field for sorting on both collections.

DEC-1277 sort

---

src/routes/AllDocumentsPage.jsx
src/routes/SearchPage.jsx
src/store/ItemStore.js

Index Page wasn't preloading items on direct link, now it will. Also changed search page to only preload if not already loaded (in case you go from index to search)
Added data checking on parent items in the item store.

DEC-1348 Index Page Fix

---

src/components/Search/AdvancedSearch.jsx
src/store/ItemStore.js

- Sorting document information alphabetically
- Only one scroll bar on search menu

DEC-1215 Advanced Search Touchups

---

src/actions/SearchActions.js
src/components/Search/AdvancedSearch.jsx
src/components/Search/DocDateSlider.jsx
src/constants/SearchActionTypes.jsx
src/modules/DeepCopy.js
src/modules/FilterBy.js
src/store/SearchStore.js

- added close button on advanced search window
- required reworking the whole window to allow for canceling changes
- renamed to advanced search filters

DEC-1215 Close button

---

src/components/Document/BackToSearchButton.jsx
src/components/Document/DocumentToolbar.jsx
src/components/Notebook/NotebookToolbar.jsx
src/store/SearchStore.js

We already had a back to search button, I just switched the document views to use it instead of the back button.
Also copied some of the styling/logic from the back button to be used in back to search.

DEC-1355 Back to search button

---

src/components/Search/Drawer.jsx

Modified drawer to use the same code path as the compare button for constructing the notebook link

Fix snackbar view link

---

src/components/Search/topics.js

Update topics file
- I wrote a little python script to parse the input for future reference. It's pretty hacky but it gets the job done.

DEC-1353 actors

---

src/components/Search/SearchBox.jsx
src/store/SearchStore.js

Changed search box to only show the filter button if the search store has some results

Disable advanced filter button when there are no search results

---

src/store/CompareStore.js

removing a compare document will clear it from the column

DEC-1360 compare clear

---

src/components/Notebook/NotebookToolbar.jsx

Float notebook toolbar to be uniform with document toolbar

DEC-1366 uniform toolbar

---

src/components/StaticAssets/HomePageNavigation.jsx
src/components/StaticAssets/Navigation.jsx
src/components/StaticPages/Contact.jsx
src/routes/ContactPage.jsx
src/routes/routes.js

This reverts commit e5003cf3521de642f44dac634f68044f5cdae058. We misunderstood how they wanted to use this form. For now we are reverting to the previous contact page.

Revert "DEC-1354:"

---

src/modules/TopicsInDocument.js

filter out unique ids (all values from the topics.js file) so they don't print

Dont print unique ids

---

src/actions/SearchActions.js
src/assets/css/csthr.scss
src/components/Document/CrowdSourcing.jsx
src/components/Document/CrowdSourcingButton.jsx
src/components/Search/AdvancedSearch.jsx
src/components/Search/Hit.jsx
src/components/Search/SearchBox.jsx
src/components/StaticAssets/FooterHome.jsx
src/components/StaticPages/Result.jsx
src/components/StaticPages/SiteIndex.jsx
src/modules/InitUser.js
src/modules/mapTermToHumanReadable.js
src/routes/InitUserPage.jsx
src/routes/routes.js

Crowdsourcing

---

.babelrc
build-conf/webpack-dev.config.js
build-conf/webpack-pprd.config.js
build-conf/webpack.config.js
package.json
yarn.lock

* IE is old and should not be used. Ever.

Babel Polyfill for IE

---

src/components/Analytics.jsx
src/components/Document/ClearSavedDocumentsButton.jsx
src/components/Document/Document.jsx
src/components/Document/DocumentNav.jsx
src/components/Document/PrintExportButton.jsx
src/components/Notebook/NotebookToolbar.jsx
src/modules/ExportSummary.js

"As a user of Convocate, I would like to be able to print results in order to incorporate paragraphs, quotations, etc in projects and papers"
* Create a button that when clicked accesses the saved items store and generates a txt file on the fly which includes metadata about the selected documents and the text of the selected paragraphs.

DEC-1433 Convocate Export/Print functionality
