src/components/Search/ListItem.jsx, src/components/Search/Search.jsx, src/routes/SearchPage.jsx
* Display name of parent article instead of individual paragraph's name
* Expand/collapse on clicking name instead of adding to notebook
* Display accurate paragraph number based on order metadata
* Hide items that don't have parents
* Increase results requested on search page to 100 instead of using Honeycomb's default of 12
=> Search Changes

src/components/Document/Document.jsx, src/components/Document/DocumentCard.jsx, src/components/Document/DocumentDialog.jsx, src/components/Notebook/NotebookDocument.jsx, src/routes/DocumentPage.jsx, src/routes/routes.js
Why: As a user of the Vatican research database, I need to be able to view a single document by itself.
How:
-Added a document route and created a DocumentPage that reuses the Document component to just render a single document. 
-Changed document to handle both child and parent objects. Ex: http://localhost:3020/document/8725e3487c, or http://localhost:3020/document/21c509b691
-Changed default style of the Document component to handle the common case (to work with both the page and dialog). The notebook now overrides the style to create the fixed height/scrolling view.
-Created a DocumentDialog that can be used to generically display a document object in a dialog window.
-Modified the DocumentCard to use the MUI additional actions buttons and connected the "View Document" action with the …
=> DEC-867: As a user of the Vatican research database, I need to be able to view a single document by itself

src/components/Notebook/NotebookList.jsx, src/components/StaticPages/SiteIndex.jsx, src/routes/Page.jsx, src/routes/SearchPage.jsx, src/routes/routes.js, src/store/ItemStore.js
This is an example of how to update the components so content only has to be preloaded once.  
1.  I added a component to the parent route / called page. 
2.  Page starts a preload of the items. 
3.  I updated Search to ask if the items are already preloaded if they are it sets its state as preloaded otherwise it waits for the event. 
4.  AND MOST IMPORTANT.  To get the router to fire correctly you must use 
import { Link } from 'react-router' 
to link to knew pages as was done in SiteIndex.
=> Dec 824 part the first.  Updating Routes so they do not reload the page all the way.

package.json, src/components/Document/Document.jsx, src/components/Document/DocumentListItem.jsx, src/components/Document/ParagraphJumpList.jsx, src/components/Notebook/NotebookDocument.jsx
Work in progress:
Highlights all selected paragraphs within document.
Placeholder version of jumplist (currently returning all paragraphs, will filter to selected paragraphs in next iteration).
Jumplist does not do any visible action, but it is setting the state on the document for the currently selected paragraph.
Next step is to get the independent scrolling sorted before enabling the jumplist to scroll to selected paragraph.
=> Dec 869 better

src/components/Search/Search.jsx, src/components/Search/SearchBox.jsx, src/components/Search/TopicFacet.jsx
Why: Search box and topics are causing a reload of the entire page, which forces it to reload all items and search hits (slow).
How: Changed the sub components of SearchPage (Search, TopicFacet, and SearchBox) to work with React router instead of changing window locations.
=> DEC-890: Speed up search components

awsbuild.sh
What: Created script that grabs the collection data from the CST and IHRL collections and deposits those files into the S3 bucket for consumption.
Why: In order to speed up the initial load process for the search interface of the CCHR research database.
=> DEC-892 Initial script to cache vatican data

src/components/Search/SearchDisplayList.jsx
Fix the way items are filtered out of the text.  Now if you filter all the nodes because they are not BodyText it will return nothing
=> Fix edge case where no documents are listed because only titles are found.

src/actions/CompareActions.js, src/components/Notebook/NotebookLink.jsx, src/constants/CompareActionTypes.jsx, src/store/CompareStore.js
Create clear columns action to clear both columns.
Use the action when clicking the link to the notebook to clear columns so old loaded data does not persist.
=> clear columns before going to the compare page

src/components/Search/Search.jsx, src/routes/SearchPage.jsx
Why: Elapsed time between changing query to re-render can be very small, depending on the search. This can cause the user to think that nothing happened. A secondary issue is that, in some cases, the results don't actually change when clicking on different topics.
How: Changed Search component to render a progress indicator any time a new search is initiated. This seems to correct both problems now that it is essentially removing the SearchDisplayList in each column from the virtual dom while waiting on search results. If we continue to have issues, we might have to dig further down into the children of Search and make sure they are all appropriately reinitializing local state data when the router re-renders the components. Also, changed the icon on the empty search to be something more …
=> DEC-896: Search list feedback

src/actions/SearchActions.js, src/assets/css/main.scss, src/assets/css/topic-nav.scss, src/components/Search/Search.jsx, src/components/Search/TopicFacet.jsx, src/components/Search/TopicFacets.jsx, src/constants/SearchActionTypes.jsx, src/routes/SearchPage.jsx, src/store/SearchStore.js
-Topics now allow multiple selections via checkboxes. Selecting/deselecting a parent will cascade to children. Children can be selected independently of the parent. 
-Search terms will now filter further on the selected topics by using logical ops for the query
There is still a little work to do such as:
1. Preserve/restore topic selections via the url
2. Expand selected topics on render
3. Tweak the appearance of checkboxes/arrows/labels
=> DEC-895: Multiselect topics

src/components/Search/SearchBox.jsx, src/components/Search/TopicFacet.jsx, src/modules/QueryParam.js, src/routes/SearchPage.jsx, src/store/SearchStore.js
Why: Under certain circumstances, the "getting started" page was not being rendered even though the user had not selected any topics/search terms.
How: There was an assumption made by users of QueryParam that it would return null if there were no params. This was only true if the param was not present. Changed it to also return null if the param is present but has no value (ex: "t=" or "q="). Also found/fixed a bug that occurred anytime the user clicked on "Search Database" from the search page.
=> DEC-912: Bugfix display getting started

src/actions/SearchActions.js
- Changed the query to no longer populate `() AND` if the topics selection is empty
- Changed the search term to no longer look for the exact phrase. The user can still qualify a phrase with quotes if they require an exact match.
- I was unable to recreate the double encoding that I found before. At one point we were getting `%2520` which suggests an `encode(encode(" "))` was occurring, but I could not recreate it, so this does not fix.
=> DEC-913: Query cleanup

src/components/Document/AddToCompare.jsx, src/components/Search/Search.jsx
Why: We're getting warnings about potential memory leaks because of all of the listeners that are registered for the same message in the EventEmitter.
How: Moved the listeners from each individual checkbox to the top level search object. Now, when any item is added/removed from comparison, the Search component will rerender all children. Their states should remain the same, so this should not affect things like changing the state of expanded cards, and it will reduce the number of listeners to two.
=> DEC-902: Bugfix max listeners

src/assets/css/document.scss, src/components/Document/Document.jsx, src/components/Document/DocumentCard.jsx, src/components/Document/ViewOriginal.jsx
What: We no longer needed the dotted menu on the results cards. That was replaced with a view document link. The view PDF option was moved to the full document modal in the upper left corner.
=> DEC-873 Place view doc / PDF link on doc modal

src/components/Document/AddToCompare.jsx, src/components/Notebook/NotebookLink.jsx, src/components/Search/Drawer.jsx, src/modules/LocalStorageExpiration.js, src/routes/SearchPage.jsx, src/store/CompareStore.js, src/store/ItemStore.js
* Rewrite Compare store to store vatican and human rights items separately in stringifyed-arrays.
* Fix drawer check on page load.
* Add a force option to expire localStorage.
* Add an item verification check and use force option on localStorageExpire if an invalid item is found.
=> DEC-886 Fix localStorage in CompareStore

src/components/Document/Document.jsx, src/components/Document/FootNotes.jsx, src/components/Document/MetadataSection.jsx
Displaying footnotes was a high priority requested feature. Since the data did not contain any actual footnote metadata until recently we were unable to format it. Now that the data exists the following changes have been made:
* Hide footnotes from metadata display section
* Add footnotes to document viewing
=> DEC-1229 Footnotes display

src/components/Search/LandingContent.jsx, src/routes/SearchPage.jsx
Moved the instructions to the landing page so that it's only rendered when no search terms are populated. This required a restyling on some of the upper level search page components that may affect other search views
=> Instructions

src/components/Document/Document.jsx
The problem is due to the item not having a "Type of Text" value. I've changed it to prevent crashing, but it may cause hidden issues. Ex: One paragraph within a large document will not have a compare button, without any discernible reason to the user.
=> Bugfix: Ecclesia document not rendering

src/components/Document/DocumentToolbar.jsx
The "back" button got longer, but the document name limit wasn't changed to match so it could push the buttons to the next line. This should fix that.
=> Alter document header width

awsbuild.sh
Changing deploy to check tags instead of branches. Doing both would get a bit messy in this script, and I'm pretty sure we want to always deploy tags to production.
=> Bugfix: Deploy tags

awsbuild.sh
There was a problem with not having updated info of the remote in order to check the current_release.
=> Bugfix: Deploy to production doesn't see correct current release

awsbuild.sh, awsbuild_pprd.sh, build_cache.sh, src/actions/ItemActions.jsx
Removed the json fetch from the build scripts, and reverted ItemActions back to querying the api. This should remove our dependency on the build scripts for fetching data.
=> Remove caching

src/components/Notebook/Notebook.jsx, src/components/StaticAssets/ClearNotebookHeaderButton.jsx, src/components/StaticAssets/Header.jsx, src/store/CompareStore.js
- Added a clear button to the header.
- Changed Header to accept an optional param to disable the clear notebook/notebook link buttons when on the Notebook page. Contextually they don't make sense here, and I had problems with the clear button not refreshing the page since the current expectation on the Notebook page when clearing docs is that it would push a new url to the history, which this button can't do. If we absolutely need it we'll have to rewrite the way that message propagates to the children of Notebook.
=> Button to clear selected from the search page

src/components/Search/SearchSort.jsx
DEC-1359 - scrollbar on entire search page on windows
DEC-1364 - sort box too big/not aligned on windows
This padding wasn't displaying on apple machines, but was causing issues on windows.
=> Fix scrollbar and sort alignment on windows

src/actions/SearchActions.js
Some topics, particularly those containing the keyword AND in them, were not being ored together correctly. This change should make sure all topics are contained in their own space and dont mess with the query keywords.
=> Correctly OR topics

src/actions/SearchActions.js, src/components/Search/SearchBox.jsx, src/components/Search/TokenSearchBox.jsx, src/constants/SearchActionTypes.jsx, src/store/SearchStore.js
Changing search string without confirming the change, then selecting a topic will now update the url to use the correct search string
Anytime the search string changes the store is now updated, but no query change event is fired. Query changes are now possible to fire separately and are done so on the appropriate actions (click search, press enter).
=> Search string update

src/components/Search/topics.js
1. Can you pull "Family Rights" and all subcategories out of both "Civil/Political" and "Economic/Social/Cultural" and put it at the same level and in between "Economic/Social/Cultural" and "Self-Determination"?
2. Can you remove "Murder" under "Violence" under "Harms/Violations"?
*These changes will fix the scenarios when the meanings are the same but the topic was found in multiple places.
=> DEC-1439 Reorganize Topics list to avoid duplication

src/components/Document/CrowdSourcing.jsx, src/components/Document/CrowdSourcingButton.jsx, src/modules/FlattenTreeToArray.js, src/modules/mapTermToHumanReadable.js
Users need to understand which of the four sections a tag originates from.
Split crowdsourcing buttons into 4 groups, one for each topic level topic. Add a heading label to each group.
Google Sheets notes:
=> DEC-1441 & DEC-1438 Break crowdsourcing buttons into groups & feedback updates
